version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER-deel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-acomplexpass}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT-5432}:5432
