name: pr
on:
  pull_request:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  statuses: write

jobs:
  pr:
    uses: letsdeel/actions-templates/.github/workflows/regression.yml@dev
    with:
      node-version: "18"
