name: push
on:
  push:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  push:
    uses: letsdeel/actions-templates/.github/workflows/publish.yml@dev
  dev-deploy:
    needs: push
    if: contains('refs/heads/dev', github.ref)
    uses: letsdeel/actions-templates/.github/workflows/trigger-gitops.yml@dev
    with:
      environment: dev
    secrets: inherit
  demo-deploy:
    needs: push
    if: contains('refs/heads/master', github.ref)
    uses: letsdeel/actions-templates/.github/workflows/trigger-gitops.yml@dev
    with:
      environment: demo
    secrets: inherit
  sales-deploy:
    needs: push
    if: contains('refs/heads/dev', github.ref)
    uses: letsdeel/actions-templates/.github/workflows/trigger-gitops.yml@dev
    with:
      environment: sales
    secrets: inherit
  prod-deploy:
    needs: push
    if: contains('refs/heads/master', github.ref)
    uses: letsdeel/actions-templates/.github/workflows/trigger-gitops.yml@dev
    with:
      environment: prod
    secrets: inherit
